gui_suffix: ""
gui_image_name: "ghcr.io/interfacerproject/interfacer-gui{{ '-' + gui_suffix if gui_suffix else '' }}"
gui_domain_name: "{{ domain_name }}"
proxy_domain_name: "proxy.{{ domain_name }}"
zenflows_domain_name: "zenflows.{{ domain_name }}"
zenflows: "https://zenflows.{{ domain_name }}"
zenflows_port: 8000
proxy_port: 20000
dpp_domain_name: "interfacer-dpp.{{ domain_name }}"
feedback_domain_name: "feedback.{{ domain_name }}"
admin_key: 7f95e9a6f9efc11f830077db88ef7752b07f4e69fca890c760fde4ed1cbb671c661ba2220608beef205bdc14265c118a1b75f61cc6cc9a01794572c90b89ba8d
room_salt: 09d988b4232a3324b128959ea2d589e47628f6b04431b6150f9a1fa089102ea67ea9ec9aa1e3475267abd8e68827fc7ae269ad246791b2bf2d4e158618ae0b3f
