gui_suffix: ""
gui_image_name: "ghcr.io/interfacerproject/interfacer-gui{{ '-' + gui_suffix if gui_suffix else '' }}"
gui_domain_name: "{{ domain_name }}"
proxy_domain_name: "proxy.{{ domain_name }}"
zenflows_domain_name: "zenflows.{{ domain_name }}"
zenflows: "https://zenflows.{{ domain_name }}"
zenflows_port: 8000
proxy_port: 20000
dpp_domain_name: "interfacer-dpp.{{ domain_name }}"
feedback_domain_name: "feedback.{{ domain_name }}"
admin_key: c8c7a06a11d30795b327a31c0c9ea45247dacad1cf0a59916b279b23278e58522f764bb3c996f9f9e1dede9f465a652e3e66e0fb23f8fec85d91cfe78b0cc90a
room_salt: fba97ae548acb5b312f44e2468d17d52dcc042320dcb5d8b8bb1446afbfb460e0788efeda65775b7fcc9272efd0a041ba9fc472761ca866d9241b1381a91fce8
